apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # <--- This is the port exposed by the service
      targetPort: 80 # <--- This is the port your container is listening on
      nodePort: 30080 # <--- This is the port you want to use
  selector:
    app: myapp