apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    # app: my-app
    # tier: front-end
    env: prod
spec:
  containers:
    - name: my-app
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
