apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: ngnix
    tier: front-end
    env: prod
spec:
  containers:
    - name: nginx-app
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
